version: '3'
services:
  node:
    build: .
    volumes:
      - ./:/usr/src/app
    command: sh -c 'cd react-practice-todo && npm start'
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
